### ISSUE TITLE
请问这个库支持免安装运行apk吗？

### ISSUE THREAD

**Issue by spysoos** [ServenScorpion/VirtualApp#28]
请问这个库支持免安装运行apk吗？

**Comment by ServenScorpion** [comment]
支持

spysoos ***@***.***> 于 2022年10月10日周一 下午4:55写道：

**Comment by spysoos** [comment]
就是不需要现在手机里安装Apk 再克隆到VA内

**Comment by spysoos** [comment]
@spysoos 看到了，我最初用了demo.apk 没看到，自己编译己有了

**Comment by ServenScorpion** [comment]
可以的

spysoos ***@***.***> 于 2022年10月12日周三 上午10:05写道：
