### ISSUE TITLE
单击桌面上的快捷方式时不起作用

### ISSUE THREAD

**Issue by dream811** [ServenScorpion/VirtualApp#35]
快捷方式图标创建成功，但点击无反应。

**Comment by ServenScorpion** [comment]
好的，好像提醒

Dream ***@***.***> 于 2023年2月22日周三 下午12:32写道：

**Comment by dream811** [comment]
![image](https://user-images.githubusercontent.com/45660446/221340092-28d05360-7ed4-41a5-aec2-c5052dce0b50.png)
http://36.41.66.150:8038/
I am not sure what is this url.
Let me give me some hint.

**Comment by ServenScorpion** [comment]
This is the server where I apply log collection to improve software
compatibility. If you cannot access the server, you should not use the
software

Dream ***@***.***> 于 2023年2月25日周六 下午1:27写道：

**Comment by dream811** [comment]
Thanks a lot!
