### ISSUE TITLE
关于安卓高版本隐藏api

### ISSUE THREAD

**Issue by eleven-di** [ServenScorpion/VirtualApp#50]
大佬是不是自己写了一套获取api的的接口,目前我找到的比较方便的方法是使用[FreeReflection](https://github.com/tiann/FreeReflection)这个库，但是他的说明里写支持到安卓14 但是我在12上还是反射失败了，不知道大佬的项目里有没有留有相关的接口，可以比较方便的调用，搜索了一下，发现都是使用jni来让系统无法识别调用栈，不知道大佬是不是也是这个思路，再次打扰大佬了

**Comment by linuxxx** [comment]
lsposed 有一个反射库, 可以看看

**Comment by eleven-di** [comment]
> lsposed 有一个反射库, 可以看看

好的谢谢，另外我想问一下项目里的虚拟定位是通过ListenerTransport来实现的，但是安卓11不可用了，有什么办法吗

**Comment by linuxxx** [comment]
具体源码没怎么看.  虚拟定位你要弄明白, 目标app的定位方式, 定位有gps和基站, 还有其他的定位方式. 知道是怎么获取定位的, 才知道怎么去fake定位.

**Comment by eleven-di** [comment]
我看它里面的流程是捕获requestLocationUpdates这个接口的实现，然后通过反射安卓底层获取到方法对象然后invoke就能触发监听器的回调了，跟什么定位方式好像没有关系，如果我理解错了请指正，非常感谢

**Comment by linuxxx** [comment]
首先通过系统api的方式获取定位,  一般也是通过系统服务, 也就是system Service来实现, android 11不支持, 那你去看下android 11, LocationManager 的实现代码不就清楚了.   其次, 这个是官方提供的获取定位的api, 很多app是不会通过官方的服务来获取定位的, 所以你还是得关注(逆向)去分析目标app获取定位的方式, 从而进行hook修改, 明白了吗

**Comment by eleven-di** [comment]
我明白你的意思，我现在主要是想理解虚拟机如何捕获并且触发定位方法的流程，并不是想单纯的修改某个app的定位，因为我发现它在安卓11以后使用requestLocationUpdates并不会触发回调方法的执行，并且发现安卓11的相关的类由ListenerTransport变成了LocationListenerTransport但是我不懂得如何修改为相关的逻辑，我新建了相关的类和判断安卓版本，但是高版本的定位方法就是无法触发，这让我很疑惑

**Comment by eleven-di** [comment]
> 这个自己看代码分析哦. 他这个是va, 还不是真实的系统, 估计是要做适配的. 另外, 他这个代码不是在aar里面吗? 你怎么修改的

有其他开源的，也是va的源码
