### ISSUE TITLE
插件的初始化代码是在哪里的  如何

### ISSUE THREAD

**Issue by jing1007209484** [ServenScorpion/VirtualApp#52]

**Comment by 111304037** [comment]
反编译能拿到，可以对比下泄露的商业版本，几本能看到他改了什么，c++部分就拿不到了，不过他c++这部分应该不会改太多

**Comment by ServenScorpion** [comment]
插件代码很简单、就一两个类、不需要反编译，github 上有的

111304037 ***@***.***> 于2023年11月22日周三 11:17写道：

**Comment by jing1007209484** [comment]
我如何在64 插件上面运行 代码
