### ISSUE TITLE
Plugin support 

### ISSUE THREAD

**Issue by noobie-devil** [ServenScorpion/VirtualApp#55]
Hi there, I'm diving into the technical aspects of source code. I've noticed similarities between the 32-bit plugin support implementation in our application and what I've seen when reverse-engineering the Multispace app. The only notable difference is how they handle their 32-bit auxiliary app by dynamically loading it with DexLoader and delegating context to the Application class of the server package.

It seems like we've taken a different approach, as when I run the project and clone the 32-bit app, the plugin support seamlessly updates within the app without requiring an additional auxiliary one.

I've also checked out the code in the SDK's lib-release.jar, generated by Android Studio, but most of it seems encrypted by stringfog. I'm trying to grasp the multi-process handling and management ideas, but it's proving quite challenging.

Do you have any insights, keywords, or suggestions on what I should focus on to achieve our initial solution (supporting a 32-bit auxiliary app) similar to what other apps are doing? Any thoughts on multi-process handling and how we can achieve both 32-bit and 64-bit processing simultaneously? Alternatively, would you be open to sharing the source code of lib-release.jar ?

Thanks for reading.

**Comment by ServenScorpion** [comment]
You need to use binder to achieve kua process communication, you only need
to get a handle, you can communicate via instant chat

noobie-devil ***@***.***> 于2024年3月1日周五 01:30写道：
