### ISSUE TITLE
请问激活码怎么获取呢

### ISSUE THREAD

**Issue by LastNever** [ServenScorpion/VirtualApp#56]

**Comment by baikaishui888** [comment]
同问,激活码

**Comment by xhwgood** [comment]
> 同问,激活码

话说你们拿到激活码了吗？

**Comment by NingQue999** [comment]
蹲

**Comment by ServenScorpion** [comment]
大家更新最新的、不需要激活码哈

**Comment by ServenScorpion** [comment]
你的版本怎么来的？github 编译出来也是23202的版本、释放的使用apk 也是23202 , 你23201
是我之前的临时版本,没有正式释放过的你怎么来的？

项鸿伟 ***@***.***> 于2024年10月7日周一 19:11写道：

**Comment by ServenScorpion** [comment]
README 里面指向的是release 目录下的文件,那个是可以与你用源码编译出来一样的,不会有升级的情况

项鸿伟 ***@***.***> 于2024年10月7日周一 21:01写道：

**Comment by xhwgood** [comment]
你 release 目录下的 apk 真的是23201，你相信我啊，现在用不了 :(

**Comment by ServenScorpion** [comment]
好的、谢谢、我看看，要不你自己 用项目编译一个吧、我也是那么编译出来放上去的、还有问题可以飞机联系我

项鸿伟 ***@***.***> 于2024年10月8日周二 08:37写道：
