### ISSUE TITLE
要怎么dlopen被双开的app的so

### ISSUE THREAD

**Issue by zeroonead** [ServenScorpion/VirtualApp#58]
直接dlopen("libxxx.so", RTLD_NOW)返回NULL了,大佬可以指点一下要怎么才能dlopen被双开的app的so吗或者不dlopen也行,找到so的基址和能够调用dlsym就可以了

**Comment by ServenScorpion** [comment]
battlesteed ***@***.***> 于2024年4月17日周三 01:21写道：

**Comment by taoyyyyyy** [comment]
xdl
